CHARACTER_ALIAS = {
    'akuma': ['aku', 'gouki'],
    'alisa': ['ali', 'als'],
    'anna': [],
    'armor_king': ['armorking', 'amk', 'ak'],
    'asuka': ['asu'],
    'bob': [],
    'bryan': ['bry'],
    'claudio': ['cld'],
    'devil_jin': ['dj', 'deviljin', 'dvj'],
    'dragunov': ['drag', 'sergei', 'dragu'],
    'eddy': ['edd'],
    'eliza': ['elz'],
    'feng': ['fen'],
    'geese': ['goose'],
    'gigas': ['ggs', 'gig'],
    'heihachi': ['hashi', 'hei', 'hessu'],
    'hwoarang': ['hwo'],
    'jack7': ['j7', 'jack-7', 'jack'],
    'jin': ['jim'],
    'josie': ['jos'],
    'julia': ['jul'],
    'katarina': ['kat'],
    'kazumi': ['kzm', 'zumi'],
    'kazuya': ['kaz', 'kazze', 'masku'],
    'king': ['kin'],
    'kuma': ['panda', 'karhu', 'bear'],
    'lars': ['lar'],
    'law': ['marshall'],
    'lee': ['violet'],
    'lei': [],
    'leo': [],
    'lili': ['lil'],
    'lucky_chloe': ['lucky', 'luckychloe', 'lck', 'lc', 'chloe'],
    'marduk': ['mdk', 'mar', 'duk'],
    'master_raven': ['masterraven', 'mraven', 'maven', 'mrv', 'raven'],
    'miguel': ['mig'],
    'negan': ['ngn', 'neg'],
    'nina': ['nin'],
    'noctis': ['noctu', 'noct', 'noc'],
    'paul': [],
    'shaheen': ['sha'],
    'steve': ['stv', 'ste', 'fox'],
    'yoshimitsu': ['yoshi', 'manji', 'yos'],
    'xiaoyu': ['xiao', 'ling'],
    'zafina': ['zaffy', 'zaf'],
    "fahkumram": ['fah', 'fahkum', 'fahk', 'fak'],
    "leroy": ['ler'],
    "ganryu": ['gan', 'ganny']
}

# Dict for searching special move types
MOVE_TYPES = {
    'ra': 'Rage art',
    'rage_art': 'Rage art',
    'rageart': 'Rage art',
    'rd': 'Rage drive',
    'rage_drive': 'Rage drive',
    'ragedrive': 'Rage drive',
    'wb': 'Wall bounce',
    'wall_bounce': 'Wall bounce',
    'wallbounce': 'Wall bounce',
    'ts': 'Tail spin',
    'tail_spin': 'Tail spin',
    'tailspin': 'Tail spin',
    'screw': 'Tail spin',
    's!': 'Tail spin',
    's': 'Tail spin',
    'homing': 'Homing',
    'homari': 'Homing',
    'armor': 'Power crush',
    'armori': 'Power crush',
    'pc': 'Power crush',
    'power': 'Power crush',
    'power_crush': 'Power crush',
    'powercrush': 'Power crush',
    'throw': 'Throw'
    'grab': 'Throw'
}

REPLACE = {
    ' ': '',
    ',': '',
    '/': '',
    'd+': 'd',
    'f+': 'f',
    'u+': 'u',
    'b+': 'b',
    'n+': 'n',
    'ws+': 'ws',
    'fc+': 'fc',
    'cd+': 'cd',
    'wr+': 'wr',
    'ra+': 'ra',
    'rd+': 'rd',
    'ss+': 'ss',
    '(': '',
    ')': ''
}
