CHARACTER_ALIAS = {
    'akuma': ['aku', 'gouki'],
    'alisa': ['ali', 'als'],
    'anna': [],
    'armor_king': ['armorking', 'amk', 'ak'],
    'asuka': ['asu'],
    'bob': [],
    'bryan': ['bry'],
    'claudio': ['cld'],
    'devil_jin': ['dj', 'deviljin', 'dvj'],
    'dragunov': ['drag', 'sergei', 'dragu'],
    'eddy': ['edd'],
    'eliza': ['elz'],
    'feng': ['fen'],
    'geese': ['goose'],
    'gigas': ['ggs', 'gig'],
    'heihachi': ['hashi', 'hei', 'hessu'],
    'hwoarang': ['hwo'],
    'jack7': ['j7', 'jack-7', 'jack'],
    'jin': ['jim'],
    'josie': ['jos'],
    'julia': ['jul'],
    'katarina': ['kat'],
    'kazumi': ['kzm', 'zumi'],
    'kazuya': ['kaz', 'kazze', 'masku'],
    'king': ['kin'],
    'kuma': ['panda', 'karhu', 'bear'],
    'lars': ['lar'],
    'law': ['marshall'],
    'lee': ['violet'],
    'lei': [],
    'leo': [],
    'lili': ['lil'],
    'lucky_chloe': ['lucky', 'luckychloe', 'lck', 'lc', 'chloe'],
    'marduk': ['mdk', 'mar', 'duk'],
    'master_raven': ['masterraven', 'mraven', 'maven', 'mrv', 'raven'],
    'miguel': ['mig'],
    'negan': ['ngn', 'neg'],
    'nina': ['nin'],
    'noctis': ['noctu', 'noct', 'noc'],
    'paul': [],
    'shaheen': ['sha'],
    'steve': ['stv', 'ste', 'fox'],
    'yoshimitsu': ['yoshi', 'manji', 'yos'],
    'xiaoyu': ['xiao', 'ling'],
    'zafina': ['zaffy', 'zaf'],
    "fahkumram": ['fah', 'fahkum', 'fahk', 'fak'],
    "leroy": ['ler'],
    "ganryu": ['gan', 'ganny']
}

MOVE_TYPES = {
    "Rage art": ["ra", "rage_art", "rageart"],
    "Rage drive": ["rd", "ragedrive", "rage_drive"],
    "Wall bounce": ["wb", "wall_bounce", "wallbounce"],
    "Tail spin": ["ts", "tail_spin", "tailspin", "screw", "s!", "s"],
    "Homing": ["homing", "homari"],
    "Power crush": ["armor", "armori", "pc", "power", "power_crush", "powercrush"],
    "Throw": ["throw", "grab"]
}

REPLACE = {
    ' ': '',
    ',': '',
    '/': '',
    'd+': 'd',
    'f+': 'f',
    'u+': 'u',
    'b+': 'b',
    'n+': 'n',
    'ws+': 'ws',
    'fc+': 'fc',
    'cd+': 'cd',
    'wr+': 'wr',
    'ra+': 'ra',
    'rd+': 'rd',
    'ss+': 'ss',
    '(': '',
    ')': ''
}
